### ISSUE TITLE
Literally quote strings with buildHelmChart

### ISSUE THREAD

**Issue by heywoodlh** [farcaller/nix-kube-generators#10]
When using `kubelib.buildHelmChart`, it seems to remove quotes. For example, I have the following defined:

```
        grafana = (kubelib.buildHelmChart {
          name = "grafana";
          chart = (nixhelm.charts { inherit pkgs; }).grafana.grafana;
          ...
          values = {
            ...
            service.annotations = {
              "tailscale.com/expose" = "true";
              "tailscale.com/hostname" = "grafana";
              "tailscale.com/tags" = "tag:http";
            };
          };
        });
```

When I build with `nix build -o result .#grafana`, the annotations are rendered like so:

```
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: grafana
    tailscale.com/tags: tag:http
```

And they get ignored when I `kubectl apply`. What I actually want is it to be rendered like so:

```
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "grafana"
    tailscale.com/tags: "tag:http"
```

I've made multiple attempts to use `builtins.toString`, or trying to escape the quotes and nothing seems to work -- I suspect that `buildHelmChart` sanitizes the output but haven't tried to track it down yet.

Any suggestions?

**Comment by farcaller** [comment]
Are you sure there's noting tinkering with your kubectl runs? 

```
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: grafana
    tailscale.com/tags: tag:http
```

This is 100% valid yaml. You only quote true, because otherwise it's parsed as a string.
